name: NodeJS with Webpack and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Build
      run: |
        npm install -g pnpm
        pnpm install
        npx webpack
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release delete latest --yes || true
        gh release create latest ./dist/desktop/bundle.js \
          --title "Latest Build" \
          --notes "This is the latest desktop build." \
          --latest
